[2019-01-22 20:00:10] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:00:50] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:01:30] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:02:10] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:02:50] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:03:30] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:04:11] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:04:51] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:05:31] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:06:11] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:06:51] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:07:31] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:08:11] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:08:51] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:09:31] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:10:11] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:10:52] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:11:32] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:12:12] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:12:52] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:13:32] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:14:12] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:14:52] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:15:32] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:16:12] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:16:52] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:17:33] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:18:13] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:18:53] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:19:33] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:20:13] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:20:53] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:21:33] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:22:13] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:22:53] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:23:33] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:24:14] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:24:54] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:25:34] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:26:14] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:26:54] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:27:34] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:28:14] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:28:54] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:29:34] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:30:14] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:30:55] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:31:35] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:32:15] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:32:55] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:33:35] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:34:15] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:34:55] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:35:35] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:36:15] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:36:55] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:37:36] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:38:16] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:38:56] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:39:36] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:40:16] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:40:56] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:41:36] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:42:16] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:42:56] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:43:36] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:44:17] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:44:57] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:45:37] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:46:17] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:46:57] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:47:37] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:48:17] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:48:57] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 20:49:21] - [Thread-2] - org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.cancel(RedisMessageListenerContainer.java:868) - Unable to unsubscribe from subscriptions
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) ~[lettuce-core-5.1.3.RELEASE.jar:?]
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114) ~[lettuce-core-5.1.3.RELEASE.jar:?]
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69) ~[lettuce-core-5.1.3.RELEASE.jar:?]
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-5.1.3.RELEASE.jar:?]
	at com.sun.proxy.$Proxy139.unsubscribe(Unknown Source) ~[?:?]
	at org.springframework.data.redis.connection.lettuce.LettuceSubscription.doClose(LettuceSubscription.java:62) ~[spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.data.redis.connection.util.AbstractSubscription.close(AbstractSubscription.java:106) ~[spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.cancel(RedisMessageListenerContainer.java:866) [spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.stop(RedisMessageListenerContainer.java:225) [spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.stop(RedisMessageListenerContainer.java:183) [spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1003) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:931) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
[2019-01-22 20:49:37] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
