[2019-01-22 19:05:14] - [HikariPool-1 housekeeper] - com.zaxxer.hikari.pool.HikariPool$HouseKeeper.run(HikariPool.java:766) - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1h2m35s611ms).
[2019-01-22 19:26:12] - [HikariPool-1 housekeeper] - com.zaxxer.hikari.pool.HikariPool$HouseKeeper.run(HikariPool.java:766) - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=20m28s188ms).
[2019-01-22 19:30:47] - [HikariPool-1 housekeeper] - com.zaxxer.hikari.pool.HikariPool$HouseKeeper.run(HikariPool.java:766) - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=4m35s221ms).
[2019-01-22 19:31:12] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:31:22] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:31:33] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:31:43] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:31:53] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:32:03] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:32:13] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:32:23] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:32:33] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:32:44] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:32:55] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:33:07] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:33:21] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:33:40] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:34:06] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:34:46] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:35:26] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:36:06] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:36:46] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:37:27] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:38:07] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:38:47] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:39:27] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:40:07] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:40:47] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:41:27] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:42:07] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:42:47] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:43:27] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:44:08] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:44:48] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:45:28] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:46:08] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:46:48] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:47:28] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:48:08] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:48:48] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:49:28] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:50:08] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:50:49] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:51:29] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:52:09] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:52:49] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:53:29] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:54:09] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:54:49] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:55:29] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:56:09] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:56:49] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:57:30] - [lettuce-nioEventLoop-4-4] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:58:10] - [lettuce-nioEventLoop-4-1] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:58:50] - [lettuce-nioEventLoop-4-2] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
[2019-01-22 19:59:30] - [lettuce-nioEventLoop-4-3] - io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:176) - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.132:6379
